### ISSUE TITLE
Not clear how rerender chart if dataset was changed.

### ISSUE THREAD

**Issue by limarchuknikita** [s0ftik3/solid-chartjs#11]
* charts not rerendered if dataset change state in runtime

**Comment by s0ftik3** [comment]
have you already seen usage examples? such as https://github.com/s0ftik3/solid-chartjs/blob/main/dev/pages/DefaultChart.tsx
Please provide more context.

**Comment by limarchuknikita** [comment]
Oh I see. I need to move my logic with chart into component with select and
I will be able do same. Thanks for example. Will try to repeat same

вс, 27 авг. 2023 г., 00:03 Vyacheslav ***@***.***>:
